### ISSUE TITLE
Phoenix6 Swerve

### ISSUE THREAD

**Issue by memori034** [Team3256/FRC_Programming_2024#32] opened 2024-01-13 01:05 UTC
Update kinematics, tune PID in SwerveConstants, implement feedforward

**Comment by realjoshuau** [comment] 2024-01-13 20:05
PERSONA 6????

**Comment by ChaoticChaosTheGreat** [comment] 2024-01-13 23:06
duplicate of advanced swerve features?

**Comment by memori034** [comment] 2024-01-14 02:44
phenix6 implementation

**Comment by memori034** [comment] 2024-01-27 23:09
@realjoshuau is feat/swerve redundant now

**Comment by memori034** [comment] 2024-01-30 01:24
implement azimuth, simulationPeriodic

**Closed** 2024-02-10 22:53 UTC
